/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.despachos_judiciales.entities.model.Despacho;
import la.netco.despachos_judiciales.entities.model.DespachoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Despacho service. Represents a row in the &quot;ADM_DESPACHOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.despachos_judiciales.entities.model.DespachoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DespachoImpl}.
 * </p>
 *
 * @author mariza
 * @see DespachoImpl
 * @see la.netco.despachos_judiciales.entities.model.Despacho
 * @see la.netco.despachos_judiciales.entities.model.DespachoModel
 * @generated
 */
public class DespachoModelImpl extends BaseModelImpl<Despacho>
	implements DespachoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a despacho model instance should use the {@link la.netco.despachos_judiciales.entities.model.Despacho} interface instead.
	 */
	public static final String TABLE_NAME = "ADM_DESPACHOS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "DES_CODIGO", Types.VARCHAR },
			{ "DES_DEPARTAMENTO", Types.INTEGER },
			{ "DES_MUNICIPIO", Types.INTEGER },
			{ "DES_ENTIDAD", Types.INTEGER },
			{ "DES_ESPECIALIDAD", Types.INTEGER },
			{ "DES_CONSECUTIVO", Types.VARCHAR },
			{ "DES_NOMBRE", Types.VARCHAR },
			{ "DES_DIRECCION", Types.VARCHAR },
			{ "DES_TELEFONOS", Types.VARCHAR },
			{ "DES_CORREO_ELECTRONICO", Types.VARCHAR },
			{ "DES_ACUERDO", Types.VARCHAR },
			{ "DES_ESTADO", Types.BIGINT },
			{ "DES_FAX", Types.VARCHAR },
			{ "DES_HORARIO_ATENCION", Types.VARCHAR },
			{ "DES_FECHA_ACT", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ADM_DESPACHOS (DES_CODIGO VARCHAR(75) not null primary key,DES_DEPARTAMENTO INTEGER,DES_MUNICIPIO INTEGER,DES_ENTIDAD INTEGER,DES_ESPECIALIDAD INTEGER,DES_CONSECUTIVO VARCHAR(75) null,DES_NOMBRE VARCHAR(75) null,DES_DIRECCION VARCHAR(75) null,DES_TELEFONOS VARCHAR(75) null,DES_CORREO_ELECTRONICO VARCHAR(75) null,DES_ACUERDO VARCHAR(75) null,DES_ESTADO LONG,DES_FAX VARCHAR(75) null,DES_HORARIO_ATENCION VARCHAR(75) null,DES_FECHA_ACT DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ADM_DESPACHOS";
	public static final String DATA_SOURCE = "csjDespachosDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.despachos_judiciales.entities.model.Despacho"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.despachos_judiciales.entities.model.Despacho"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.despachos_judiciales.entities.model.Despacho"));

	public DespachoModelImpl() {
	}

	public String getPrimaryKey() {
		return _codigo;
	}

	public void setPrimaryKey(String primaryKey) {
		setCodigo(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _codigo;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return Despacho.class;
	}

	public String getModelClassName() {
		return Despacho.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("codigo", getCodigo());
		attributes.put("idDepartamento", getIdDepartamento());
		attributes.put("idMunicipio", getIdMunicipio());
		attributes.put("idEntidad", getIdEntidad());
		attributes.put("idEspecialidad", getIdEspecialidad());
		attributes.put("consecutivo", getConsecutivo());
		attributes.put("nombre", getNombre());
		attributes.put("direccion", getDireccion());
		attributes.put("telefonos", getTelefonos());
		attributes.put("correo_electronico", getCorreo_electronico());
		attributes.put("acuerdo", getAcuerdo());
		attributes.put("estado", getEstado());
		attributes.put("fax", getFax());
		attributes.put("horario_atencion", getHorario_atencion());
		attributes.put("fecha_act", getFecha_act());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String codigo = (String)attributes.get("codigo");

		if (codigo != null) {
			setCodigo(codigo);
		}

		Integer idDepartamento = (Integer)attributes.get("idDepartamento");

		if (idDepartamento != null) {
			setIdDepartamento(idDepartamento);
		}

		Integer idMunicipio = (Integer)attributes.get("idMunicipio");

		if (idMunicipio != null) {
			setIdMunicipio(idMunicipio);
		}

		Integer idEntidad = (Integer)attributes.get("idEntidad");

		if (idEntidad != null) {
			setIdEntidad(idEntidad);
		}

		Integer idEspecialidad = (Integer)attributes.get("idEspecialidad");

		if (idEspecialidad != null) {
			setIdEspecialidad(idEspecialidad);
		}

		String consecutivo = (String)attributes.get("consecutivo");

		if (consecutivo != null) {
			setConsecutivo(consecutivo);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}

		String direccion = (String)attributes.get("direccion");

		if (direccion != null) {
			setDireccion(direccion);
		}

		String telefonos = (String)attributes.get("telefonos");

		if (telefonos != null) {
			setTelefonos(telefonos);
		}

		String correo_electronico = (String)attributes.get("correo_electronico");

		if (correo_electronico != null) {
			setCorreo_electronico(correo_electronico);
		}

		String acuerdo = (String)attributes.get("acuerdo");

		if (acuerdo != null) {
			setAcuerdo(acuerdo);
		}

		Long estado = (Long)attributes.get("estado");

		if (estado != null) {
			setEstado(estado);
		}

		String fax = (String)attributes.get("fax");

		if (fax != null) {
			setFax(fax);
		}

		String horario_atencion = (String)attributes.get("horario_atencion");

		if (horario_atencion != null) {
			setHorario_atencion(horario_atencion);
		}

		Date fecha_act = (Date)attributes.get("fecha_act");

		if (fecha_act != null) {
			setFecha_act(fecha_act);
		}
	}

	public String getCodigo() {
		if (_codigo == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigo;
		}
	}

	public void setCodigo(String codigo) {
		_codigo = codigo;
	}

	public int getIdDepartamento() {
		return _idDepartamento;
	}

	public void setIdDepartamento(int idDepartamento) {
		_idDepartamento = idDepartamento;
	}

	public int getIdMunicipio() {
		return _idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		_idMunicipio = idMunicipio;
	}

	public int getIdEntidad() {
		return _idEntidad;
	}

	public void setIdEntidad(int idEntidad) {
		_idEntidad = idEntidad;
	}

	public int getIdEspecialidad() {
		return _idEspecialidad;
	}

	public void setIdEspecialidad(int idEspecialidad) {
		_idEspecialidad = idEspecialidad;
	}

	public String getConsecutivo() {
		if (_consecutivo == null) {
			return StringPool.BLANK;
		}
		else {
			return _consecutivo;
		}
	}

	public void setConsecutivo(String consecutivo) {
		_consecutivo = consecutivo;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	public String getDireccion() {
		if (_direccion == null) {
			return StringPool.BLANK;
		}
		else {
			return _direccion;
		}
	}

	public void setDireccion(String direccion) {
		_direccion = direccion;
	}

	public String getTelefonos() {
		if (_telefonos == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefonos;
		}
	}

	public void setTelefonos(String telefonos) {
		_telefonos = telefonos;
	}

	public String getCorreo_electronico() {
		if (_correo_electronico == null) {
			return StringPool.BLANK;
		}
		else {
			return _correo_electronico;
		}
	}

	public void setCorreo_electronico(String correo_electronico) {
		_correo_electronico = correo_electronico;
	}

	public String getAcuerdo() {
		if (_acuerdo == null) {
			return StringPool.BLANK;
		}
		else {
			return _acuerdo;
		}
	}

	public void setAcuerdo(String acuerdo) {
		_acuerdo = acuerdo;
	}

	public long getEstado() {
		return _estado;
	}

	public void setEstado(long estado) {
		_estado = estado;
	}

	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	public void setFax(String fax) {
		_fax = fax;
	}

	public String getHorario_atencion() {
		if (_horario_atencion == null) {
			return StringPool.BLANK;
		}
		else {
			return _horario_atencion;
		}
	}

	public void setHorario_atencion(String horario_atencion) {
		_horario_atencion = horario_atencion;
	}

	public Date getFecha_act() {
		return _fecha_act;
	}

	public void setFecha_act(Date fecha_act) {
		_fecha_act = fecha_act;
	}

	@Override
	public Despacho toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Despacho)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		DespachoImpl despachoImpl = new DespachoImpl();

		despachoImpl.setCodigo(getCodigo());
		despachoImpl.setIdDepartamento(getIdDepartamento());
		despachoImpl.setIdMunicipio(getIdMunicipio());
		despachoImpl.setIdEntidad(getIdEntidad());
		despachoImpl.setIdEspecialidad(getIdEspecialidad());
		despachoImpl.setConsecutivo(getConsecutivo());
		despachoImpl.setNombre(getNombre());
		despachoImpl.setDireccion(getDireccion());
		despachoImpl.setTelefonos(getTelefonos());
		despachoImpl.setCorreo_electronico(getCorreo_electronico());
		despachoImpl.setAcuerdo(getAcuerdo());
		despachoImpl.setEstado(getEstado());
		despachoImpl.setFax(getFax());
		despachoImpl.setHorario_atencion(getHorario_atencion());
		despachoImpl.setFecha_act(getFecha_act());

		despachoImpl.resetOriginalValues();

		return despachoImpl;
	}

	public int compareTo(Despacho despacho) {
		String primaryKey = despacho.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Despacho despacho = null;

		try {
			despacho = (Despacho)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = despacho.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Despacho> toCacheModel() {
		DespachoCacheModel despachoCacheModel = new DespachoCacheModel();

		despachoCacheModel.codigo = getCodigo();

		String codigo = despachoCacheModel.codigo;

		if ((codigo != null) && (codigo.length() == 0)) {
			despachoCacheModel.codigo = null;
		}

		despachoCacheModel.idDepartamento = getIdDepartamento();

		despachoCacheModel.idMunicipio = getIdMunicipio();

		despachoCacheModel.idEntidad = getIdEntidad();

		despachoCacheModel.idEspecialidad = getIdEspecialidad();

		despachoCacheModel.consecutivo = getConsecutivo();

		String consecutivo = despachoCacheModel.consecutivo;

		if ((consecutivo != null) && (consecutivo.length() == 0)) {
			despachoCacheModel.consecutivo = null;
		}

		despachoCacheModel.nombre = getNombre();

		String nombre = despachoCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			despachoCacheModel.nombre = null;
		}

		despachoCacheModel.direccion = getDireccion();

		String direccion = despachoCacheModel.direccion;

		if ((direccion != null) && (direccion.length() == 0)) {
			despachoCacheModel.direccion = null;
		}

		despachoCacheModel.telefonos = getTelefonos();

		String telefonos = despachoCacheModel.telefonos;

		if ((telefonos != null) && (telefonos.length() == 0)) {
			despachoCacheModel.telefonos = null;
		}

		despachoCacheModel.correo_electronico = getCorreo_electronico();

		String correo_electronico = despachoCacheModel.correo_electronico;

		if ((correo_electronico != null) && (correo_electronico.length() == 0)) {
			despachoCacheModel.correo_electronico = null;
		}

		despachoCacheModel.acuerdo = getAcuerdo();

		String acuerdo = despachoCacheModel.acuerdo;

		if ((acuerdo != null) && (acuerdo.length() == 0)) {
			despachoCacheModel.acuerdo = null;
		}

		despachoCacheModel.estado = getEstado();

		despachoCacheModel.fax = getFax();

		String fax = despachoCacheModel.fax;

		if ((fax != null) && (fax.length() == 0)) {
			despachoCacheModel.fax = null;
		}

		despachoCacheModel.horario_atencion = getHorario_atencion();

		String horario_atencion = despachoCacheModel.horario_atencion;

		if ((horario_atencion != null) && (horario_atencion.length() == 0)) {
			despachoCacheModel.horario_atencion = null;
		}

		Date fecha_act = getFecha_act();

		if (fecha_act != null) {
			despachoCacheModel.fecha_act = fecha_act.getTime();
		}
		else {
			despachoCacheModel.fecha_act = Long.MIN_VALUE;
		}

		return despachoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{codigo=");
		sb.append(getCodigo());
		sb.append(", idDepartamento=");
		sb.append(getIdDepartamento());
		sb.append(", idMunicipio=");
		sb.append(getIdMunicipio());
		sb.append(", idEntidad=");
		sb.append(getIdEntidad());
		sb.append(", idEspecialidad=");
		sb.append(getIdEspecialidad());
		sb.append(", consecutivo=");
		sb.append(getConsecutivo());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append(", direccion=");
		sb.append(getDireccion());
		sb.append(", telefonos=");
		sb.append(getTelefonos());
		sb.append(", correo_electronico=");
		sb.append(getCorreo_electronico());
		sb.append(", acuerdo=");
		sb.append(getAcuerdo());
		sb.append(", estado=");
		sb.append(getEstado());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", horario_atencion=");
		sb.append(getHorario_atencion());
		sb.append(", fecha_act=");
		sb.append(getFecha_act());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("la.netco.despachos_judiciales.entities.model.Despacho");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>codigo</column-name><column-value><![CDATA[");
		sb.append(getCodigo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idDepartamento</column-name><column-value><![CDATA[");
		sb.append(getIdDepartamento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idMunicipio</column-name><column-value><![CDATA[");
		sb.append(getIdMunicipio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idEntidad</column-name><column-value><![CDATA[");
		sb.append(getIdEntidad());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idEspecialidad</column-name><column-value><![CDATA[");
		sb.append(getIdEspecialidad());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>consecutivo</column-name><column-value><![CDATA[");
		sb.append(getConsecutivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>direccion</column-name><column-value><![CDATA[");
		sb.append(getDireccion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefonos</column-name><column-value><![CDATA[");
		sb.append(getTelefonos());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>correo_electronico</column-name><column-value><![CDATA[");
		sb.append(getCorreo_electronico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>acuerdo</column-name><column-value><![CDATA[");
		sb.append(getAcuerdo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estado</column-name><column-value><![CDATA[");
		sb.append(getEstado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>horario_atencion</column-name><column-value><![CDATA[");
		sb.append(getHorario_atencion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_act</column-name><column-value><![CDATA[");
		sb.append(getFecha_act());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Despacho.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Despacho.class
		};
	private String _codigo;
	private int _idDepartamento;
	private int _idMunicipio;
	private int _idEntidad;
	private int _idEspecialidad;
	private String _consecutivo;
	private String _nombre;
	private String _direccion;
	private String _telefonos;
	private String _correo_electronico;
	private String _acuerdo;
	private long _estado;
	private String _fax;
	private String _horario_atencion;
	private Date _fecha_act;
	private Despacho _escapedModelProxy;
}