/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ConsejoSeccional service. Represents a row in the &quot;GLO_CONSEJOS_SEC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.despachos_judiciales.entities.model.impl.ConsejoSeccionalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.despachos_judiciales.entities.model.impl.ConsejoSeccionalImpl}.
 * </p>
 *
 * @author mariza
 * @see ConsejoSeccional
 * @see la.netco.despachos_judiciales.entities.model.impl.ConsejoSeccionalImpl
 * @see la.netco.despachos_judiciales.entities.model.impl.ConsejoSeccionalModelImpl
 * @generated
 */
public interface ConsejoSeccionalModel extends BaseModel<ConsejoSeccional> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a consejo seccional model instance should use the {@link ConsejoSeccional} interface instead.
	 */

	/**
	 * Returns the primary key of this consejo seccional.
	 *
	 * @return the primary key of this consejo seccional
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this consejo seccional.
	 *
	 * @param primaryKey the primary key of this consejo seccional
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the codigo of this consejo seccional.
	 *
	 * @return the codigo of this consejo seccional
	 */
	public int getCodigo();

	/**
	 * Sets the codigo of this consejo seccional.
	 *
	 * @param codigo the codigo of this consejo seccional
	 */
	public void setCodigo(int codigo);

	/**
	 * Returns the nombre of this consejo seccional.
	 *
	 * @return the nombre of this consejo seccional
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this consejo seccional.
	 *
	 * @param nombre the nombre of this consejo seccional
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the direccion of this consejo seccional.
	 *
	 * @return the direccion of this consejo seccional
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this consejo seccional.
	 *
	 * @param direccion the direccion of this consejo seccional
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the telefonos of this consejo seccional.
	 *
	 * @return the telefonos of this consejo seccional
	 */
	@AutoEscape
	public String getTelefonos();

	/**
	 * Sets the telefonos of this consejo seccional.
	 *
	 * @param telefonos the telefonos of this consejo seccional
	 */
	public void setTelefonos(String telefonos);

	/**
	 * Returns the correo_electronico of this consejo seccional.
	 *
	 * @return the correo_electronico of this consejo seccional
	 */
	@AutoEscape
	public String getCorreo_electronico();

	/**
	 * Sets the correo_electronico of this consejo seccional.
	 *
	 * @param correo_electronico the correo_electronico of this consejo seccional
	 */
	public void setCorreo_electronico(String correo_electronico);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ConsejoSeccional consejoSeccional);

	public int hashCode();

	public CacheModel<ConsejoSeccional> toCacheModel();

	public ConsejoSeccional toEscapedModel();

	public String toString();

	public String toXmlString();
}