/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.despachos_judiciales.entities.model.ConsejoSeccional;
import la.netco.despachos_judiciales.entities.model.ConsejoSeccionalModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ConsejoSeccional service. Represents a row in the &quot;GLO_CONSEJOS_SEC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.despachos_judiciales.entities.model.ConsejoSeccionalModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsejoSeccionalImpl}.
 * </p>
 *
 * @author mariza
 * @see ConsejoSeccionalImpl
 * @see la.netco.despachos_judiciales.entities.model.ConsejoSeccional
 * @see la.netco.despachos_judiciales.entities.model.ConsejoSeccionalModel
 * @generated
 */
public class ConsejoSeccionalModelImpl extends BaseModelImpl<ConsejoSeccional>
	implements ConsejoSeccionalModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a consejo seccional model instance should use the {@link la.netco.despachos_judiciales.entities.model.ConsejoSeccional} interface instead.
	 */
	public static final String TABLE_NAME = "GLO_CONSEJOS_SEC";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CON_CODIGO", Types.INTEGER },
			{ "CON_NOMBRE", Types.VARCHAR },
			{ "CON_DIRECCION", Types.VARCHAR },
			{ "CON_TELEFONOS", Types.VARCHAR },
			{ "CON_CORREO_ELECTRONICO", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GLO_CONSEJOS_SEC (CON_CODIGO INTEGER not null primary key,CON_NOMBRE VARCHAR(75) null,CON_DIRECCION VARCHAR(75) null,CON_TELEFONOS VARCHAR(75) null,CON_CORREO_ELECTRONICO VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GLO_CONSEJOS_SEC";
	public static final String DATA_SOURCE = "csjDespachosDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.despachos_judiciales.entities.model.ConsejoSeccional"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.despachos_judiciales.entities.model.ConsejoSeccional"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.despachos_judiciales.entities.model.ConsejoSeccional"));

	public ConsejoSeccionalModelImpl() {
	}

	public int getPrimaryKey() {
		return _codigo;
	}

	public void setPrimaryKey(int primaryKey) {
		setCodigo(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_codigo);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return ConsejoSeccional.class;
	}

	public String getModelClassName() {
		return ConsejoSeccional.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("codigo", getCodigo());
		attributes.put("nombre", getNombre());
		attributes.put("direccion", getDireccion());
		attributes.put("telefonos", getTelefonos());
		attributes.put("correo_electronico", getCorreo_electronico());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer codigo = (Integer)attributes.get("codigo");

		if (codigo != null) {
			setCodigo(codigo);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}

		String direccion = (String)attributes.get("direccion");

		if (direccion != null) {
			setDireccion(direccion);
		}

		String telefonos = (String)attributes.get("telefonos");

		if (telefonos != null) {
			setTelefonos(telefonos);
		}

		String correo_electronico = (String)attributes.get("correo_electronico");

		if (correo_electronico != null) {
			setCorreo_electronico(correo_electronico);
		}
	}

	public int getCodigo() {
		return _codigo;
	}

	public void setCodigo(int codigo) {
		_codigo = codigo;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	public String getDireccion() {
		if (_direccion == null) {
			return StringPool.BLANK;
		}
		else {
			return _direccion;
		}
	}

	public void setDireccion(String direccion) {
		_direccion = direccion;
	}

	public String getTelefonos() {
		if (_telefonos == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefonos;
		}
	}

	public void setTelefonos(String telefonos) {
		_telefonos = telefonos;
	}

	public String getCorreo_electronico() {
		if (_correo_electronico == null) {
			return StringPool.BLANK;
		}
		else {
			return _correo_electronico;
		}
	}

	public void setCorreo_electronico(String correo_electronico) {
		_correo_electronico = correo_electronico;
	}

	@Override
	public ConsejoSeccional toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ConsejoSeccional)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ConsejoSeccionalImpl consejoSeccionalImpl = new ConsejoSeccionalImpl();

		consejoSeccionalImpl.setCodigo(getCodigo());
		consejoSeccionalImpl.setNombre(getNombre());
		consejoSeccionalImpl.setDireccion(getDireccion());
		consejoSeccionalImpl.setTelefonos(getTelefonos());
		consejoSeccionalImpl.setCorreo_electronico(getCorreo_electronico());

		consejoSeccionalImpl.resetOriginalValues();

		return consejoSeccionalImpl;
	}

	public int compareTo(ConsejoSeccional consejoSeccional) {
		int primaryKey = consejoSeccional.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ConsejoSeccional consejoSeccional = null;

		try {
			consejoSeccional = (ConsejoSeccional)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = consejoSeccional.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ConsejoSeccional> toCacheModel() {
		ConsejoSeccionalCacheModel consejoSeccionalCacheModel = new ConsejoSeccionalCacheModel();

		consejoSeccionalCacheModel.codigo = getCodigo();

		consejoSeccionalCacheModel.nombre = getNombre();

		String nombre = consejoSeccionalCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			consejoSeccionalCacheModel.nombre = null;
		}

		consejoSeccionalCacheModel.direccion = getDireccion();

		String direccion = consejoSeccionalCacheModel.direccion;

		if ((direccion != null) && (direccion.length() == 0)) {
			consejoSeccionalCacheModel.direccion = null;
		}

		consejoSeccionalCacheModel.telefonos = getTelefonos();

		String telefonos = consejoSeccionalCacheModel.telefonos;

		if ((telefonos != null) && (telefonos.length() == 0)) {
			consejoSeccionalCacheModel.telefonos = null;
		}

		consejoSeccionalCacheModel.correo_electronico = getCorreo_electronico();

		String correo_electronico = consejoSeccionalCacheModel.correo_electronico;

		if ((correo_electronico != null) && (correo_electronico.length() == 0)) {
			consejoSeccionalCacheModel.correo_electronico = null;
		}

		return consejoSeccionalCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{codigo=");
		sb.append(getCodigo());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append(", direccion=");
		sb.append(getDireccion());
		sb.append(", telefonos=");
		sb.append(getTelefonos());
		sb.append(", correo_electronico=");
		sb.append(getCorreo_electronico());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append(
			"la.netco.despachos_judiciales.entities.model.ConsejoSeccional");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>codigo</column-name><column-value><![CDATA[");
		sb.append(getCodigo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>direccion</column-name><column-value><![CDATA[");
		sb.append(getDireccion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefonos</column-name><column-value><![CDATA[");
		sb.append(getTelefonos());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>correo_electronico</column-name><column-value><![CDATA[");
		sb.append(getCorreo_electronico());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ConsejoSeccional.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ConsejoSeccional.class
		};
	private int _codigo;
	private String _nombre;
	private String _direccion;
	private String _telefonos;
	private String _correo_electronico;
	private ConsejoSeccional _escapedModelProxy;
}