/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespacho;
import la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespachoModel;
import la.netco.despachos_judiciales.entities.service.persistence.RelacionTrabajadorDespachoPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the RelacionTrabajadorDespacho service. Represents a row in the &quot;REL_TRA_DES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespachoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RelacionTrabajadorDespachoImpl}.
 * </p>
 *
 * @author mariza
 * @see RelacionTrabajadorDespachoImpl
 * @see la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespacho
 * @see la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespachoModel
 * @generated
 */
public class RelacionTrabajadorDespachoModelImpl extends BaseModelImpl<RelacionTrabajadorDespacho>
	implements RelacionTrabajadorDespachoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a relacion trabajador despacho model instance should use the {@link la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespacho} interface instead.
	 */
	public static final String TABLE_NAME = "REL_TRA_DES";
	public static final Object[][] TABLE_COLUMNS = {
			{ "TDE_DESPACHO", Types.VARCHAR },
			{ "TDE_TRABAJADOR", Types.VARCHAR },
			{ "TDE_CARGO", Types.VARCHAR },
			{ "TDE_ACUERDO", Types.VARCHAR },
			{ "TDE_ACTIVO", Types.VARCHAR },
			{ "TDE_FECHA_INI", Types.VARCHAR },
			{ "TDE_FECHA_FIN", Types.VARCHAR },
			{ "TDE_SECUENCIA", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table REL_TRA_DES (TDE_DESPACHO VARCHAR(75) not null,TDE_TRABAJADOR VARCHAR(75) not null,TDE_CARGO VARCHAR(75) null,TDE_ACUERDO VARCHAR(75) null,TDE_ACTIVO VARCHAR(75) null,TDE_FECHA_INI VARCHAR(75) null,TDE_FECHA_FIN VARCHAR(75) null,TDE_SECUENCIA VARCHAR(75) null,primary key (TDE_DESPACHO, TDE_TRABAJADOR))";
	public static final String TABLE_SQL_DROP = "drop table REL_TRA_DES";
	public static final String DATA_SOURCE = "csjDespachosDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespacho"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespacho"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespacho"));

	public RelacionTrabajadorDespachoModelImpl() {
	}

	public RelacionTrabajadorDespachoPK getPrimaryKey() {
		return new RelacionTrabajadorDespachoPK(_idDespacho, _idTrabajador);
	}

	public void setPrimaryKey(RelacionTrabajadorDespachoPK primaryKey) {
		setIdDespacho(primaryKey.idDespacho);
		setIdTrabajador(primaryKey.idTrabajador);
	}

	public Serializable getPrimaryKeyObj() {
		return new RelacionTrabajadorDespachoPK(_idDespacho, _idTrabajador);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((RelacionTrabajadorDespachoPK)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return RelacionTrabajadorDespacho.class;
	}

	public String getModelClassName() {
		return RelacionTrabajadorDespacho.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idDespacho", getIdDespacho());
		attributes.put("idTrabajador", getIdTrabajador());
		attributes.put("cargo", getCargo());
		attributes.put("acuerdo", getAcuerdo());
		attributes.put("activo", getActivo());
		attributes.put("fecha_ini", getFecha_ini());
		attributes.put("fecha_fin", getFecha_fin());
		attributes.put("secuencia", getSecuencia());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String idDespacho = (String)attributes.get("idDespacho");

		if (idDespacho != null) {
			setIdDespacho(idDespacho);
		}

		String idTrabajador = (String)attributes.get("idTrabajador");

		if (idTrabajador != null) {
			setIdTrabajador(idTrabajador);
		}

		String cargo = (String)attributes.get("cargo");

		if (cargo != null) {
			setCargo(cargo);
		}

		String acuerdo = (String)attributes.get("acuerdo");

		if (acuerdo != null) {
			setAcuerdo(acuerdo);
		}

		String activo = (String)attributes.get("activo");

		if (activo != null) {
			setActivo(activo);
		}

		String fecha_ini = (String)attributes.get("fecha_ini");

		if (fecha_ini != null) {
			setFecha_ini(fecha_ini);
		}

		String fecha_fin = (String)attributes.get("fecha_fin");

		if (fecha_fin != null) {
			setFecha_fin(fecha_fin);
		}

		String secuencia = (String)attributes.get("secuencia");

		if (secuencia != null) {
			setSecuencia(secuencia);
		}
	}

	public String getIdDespacho() {
		if (_idDespacho == null) {
			return StringPool.BLANK;
		}
		else {
			return _idDespacho;
		}
	}

	public void setIdDespacho(String idDespacho) {
		_idDespacho = idDespacho;
	}

	public String getIdTrabajador() {
		if (_idTrabajador == null) {
			return StringPool.BLANK;
		}
		else {
			return _idTrabajador;
		}
	}

	public void setIdTrabajador(String idTrabajador) {
		_idTrabajador = idTrabajador;
	}

	public String getCargo() {
		if (_cargo == null) {
			return StringPool.BLANK;
		}
		else {
			return _cargo;
		}
	}

	public void setCargo(String cargo) {
		_cargo = cargo;
	}

	public String getAcuerdo() {
		if (_acuerdo == null) {
			return StringPool.BLANK;
		}
		else {
			return _acuerdo;
		}
	}

	public void setAcuerdo(String acuerdo) {
		_acuerdo = acuerdo;
	}

	public String getActivo() {
		if (_activo == null) {
			return StringPool.BLANK;
		}
		else {
			return _activo;
		}
	}

	public void setActivo(String activo) {
		_activo = activo;
	}

	public String getFecha_ini() {
		if (_fecha_ini == null) {
			return StringPool.BLANK;
		}
		else {
			return _fecha_ini;
		}
	}

	public void setFecha_ini(String fecha_ini) {
		_fecha_ini = fecha_ini;
	}

	public String getFecha_fin() {
		if (_fecha_fin == null) {
			return StringPool.BLANK;
		}
		else {
			return _fecha_fin;
		}
	}

	public void setFecha_fin(String fecha_fin) {
		_fecha_fin = fecha_fin;
	}

	public String getSecuencia() {
		if (_secuencia == null) {
			return StringPool.BLANK;
		}
		else {
			return _secuencia;
		}
	}

	public void setSecuencia(String secuencia) {
		_secuencia = secuencia;
	}

	@Override
	public RelacionTrabajadorDespacho toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (RelacionTrabajadorDespacho)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		RelacionTrabajadorDespachoImpl relacionTrabajadorDespachoImpl = new RelacionTrabajadorDespachoImpl();

		relacionTrabajadorDespachoImpl.setIdDespacho(getIdDespacho());
		relacionTrabajadorDespachoImpl.setIdTrabajador(getIdTrabajador());
		relacionTrabajadorDespachoImpl.setCargo(getCargo());
		relacionTrabajadorDespachoImpl.setAcuerdo(getAcuerdo());
		relacionTrabajadorDespachoImpl.setActivo(getActivo());
		relacionTrabajadorDespachoImpl.setFecha_ini(getFecha_ini());
		relacionTrabajadorDespachoImpl.setFecha_fin(getFecha_fin());
		relacionTrabajadorDespachoImpl.setSecuencia(getSecuencia());

		relacionTrabajadorDespachoImpl.resetOriginalValues();

		return relacionTrabajadorDespachoImpl;
	}

	public int compareTo(RelacionTrabajadorDespacho relacionTrabajadorDespacho) {
		RelacionTrabajadorDespachoPK primaryKey = relacionTrabajadorDespacho.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		RelacionTrabajadorDespacho relacionTrabajadorDespacho = null;

		try {
			relacionTrabajadorDespacho = (RelacionTrabajadorDespacho)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		RelacionTrabajadorDespachoPK primaryKey = relacionTrabajadorDespacho.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RelacionTrabajadorDespacho> toCacheModel() {
		RelacionTrabajadorDespachoCacheModel relacionTrabajadorDespachoCacheModel =
			new RelacionTrabajadorDespachoCacheModel();

		relacionTrabajadorDespachoCacheModel.idDespacho = getIdDespacho();

		String idDespacho = relacionTrabajadorDespachoCacheModel.idDespacho;

		if ((idDespacho != null) && (idDespacho.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.idDespacho = null;
		}

		relacionTrabajadorDespachoCacheModel.idTrabajador = getIdTrabajador();

		String idTrabajador = relacionTrabajadorDespachoCacheModel.idTrabajador;

		if ((idTrabajador != null) && (idTrabajador.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.idTrabajador = null;
		}

		relacionTrabajadorDespachoCacheModel.cargo = getCargo();

		String cargo = relacionTrabajadorDespachoCacheModel.cargo;

		if ((cargo != null) && (cargo.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.cargo = null;
		}

		relacionTrabajadorDespachoCacheModel.acuerdo = getAcuerdo();

		String acuerdo = relacionTrabajadorDespachoCacheModel.acuerdo;

		if ((acuerdo != null) && (acuerdo.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.acuerdo = null;
		}

		relacionTrabajadorDespachoCacheModel.activo = getActivo();

		String activo = relacionTrabajadorDespachoCacheModel.activo;

		if ((activo != null) && (activo.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.activo = null;
		}

		relacionTrabajadorDespachoCacheModel.fecha_ini = getFecha_ini();

		String fecha_ini = relacionTrabajadorDespachoCacheModel.fecha_ini;

		if ((fecha_ini != null) && (fecha_ini.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.fecha_ini = null;
		}

		relacionTrabajadorDespachoCacheModel.fecha_fin = getFecha_fin();

		String fecha_fin = relacionTrabajadorDespachoCacheModel.fecha_fin;

		if ((fecha_fin != null) && (fecha_fin.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.fecha_fin = null;
		}

		relacionTrabajadorDespachoCacheModel.secuencia = getSecuencia();

		String secuencia = relacionTrabajadorDespachoCacheModel.secuencia;

		if ((secuencia != null) && (secuencia.length() == 0)) {
			relacionTrabajadorDespachoCacheModel.secuencia = null;
		}

		return relacionTrabajadorDespachoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{idDespacho=");
		sb.append(getIdDespacho());
		sb.append(", idTrabajador=");
		sb.append(getIdTrabajador());
		sb.append(", cargo=");
		sb.append(getCargo());
		sb.append(", acuerdo=");
		sb.append(getAcuerdo());
		sb.append(", activo=");
		sb.append(getActivo());
		sb.append(", fecha_ini=");
		sb.append(getFecha_ini());
		sb.append(", fecha_fin=");
		sb.append(getFecha_fin());
		sb.append(", secuencia=");
		sb.append(getSecuencia());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append(
			"la.netco.despachos_judiciales.entities.model.RelacionTrabajadorDespacho");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idDespacho</column-name><column-value><![CDATA[");
		sb.append(getIdDespacho());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idTrabajador</column-name><column-value><![CDATA[");
		sb.append(getIdTrabajador());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cargo</column-name><column-value><![CDATA[");
		sb.append(getCargo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>acuerdo</column-name><column-value><![CDATA[");
		sb.append(getAcuerdo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>activo</column-name><column-value><![CDATA[");
		sb.append(getActivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_ini</column-name><column-value><![CDATA[");
		sb.append(getFecha_ini());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_fin</column-name><column-value><![CDATA[");
		sb.append(getFecha_fin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secuencia</column-name><column-value><![CDATA[");
		sb.append(getSecuencia());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RelacionTrabajadorDespacho.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			RelacionTrabajadorDespacho.class
		};
	private String _idDespacho;
	private String _idTrabajador;
	private String _cargo;
	private String _acuerdo;
	private String _activo;
	private String _fecha_ini;
	private String _fecha_fin;
	private String _secuencia;
	private RelacionTrabajadorDespacho _escapedModelProxy;
}