/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import la.netco.despachos_judiciales.entities.service.persistence.MunicipioPK;

import java.io.Serializable;

/**
 * The base model interface for the Municipio service. Represents a row in the &quot;GLO_MUNICIPIOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.despachos_judiciales.entities.model.impl.MunicipioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.despachos_judiciales.entities.model.impl.MunicipioImpl}.
 * </p>
 *
 * @author mariza
 * @see Municipio
 * @see la.netco.despachos_judiciales.entities.model.impl.MunicipioImpl
 * @see la.netco.despachos_judiciales.entities.model.impl.MunicipioModelImpl
 * @generated
 */
public interface MunicipioModel extends BaseModel<Municipio> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a municipio model instance should use the {@link Municipio} interface instead.
	 */

	/**
	 * Returns the primary key of this municipio.
	 *
	 * @return the primary key of this municipio
	 */
	public MunicipioPK getPrimaryKey();

	/**
	 * Sets the primary key of this municipio.
	 *
	 * @param primaryKey the primary key of this municipio
	 */
	public void setPrimaryKey(MunicipioPK primaryKey);

	/**
	 * Returns the id departamento of this municipio.
	 *
	 * @return the id departamento of this municipio
	 */
	public int getIdDepartamento();

	/**
	 * Sets the id departamento of this municipio.
	 *
	 * @param idDepartamento the id departamento of this municipio
	 */
	public void setIdDepartamento(int idDepartamento);

	/**
	 * Returns the codigo of this municipio.
	 *
	 * @return the codigo of this municipio
	 */
	public int getCodigo();

	/**
	 * Sets the codigo of this municipio.
	 *
	 * @param codigo the codigo of this municipio
	 */
	public void setCodigo(int codigo);

	/**
	 * Returns the nombre of this municipio.
	 *
	 * @return the nombre of this municipio
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this municipio.
	 *
	 * @param nombre the nombre of this municipio
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the indicativo of this municipio.
	 *
	 * @return the indicativo of this municipio
	 */
	public int getIndicativo();

	/**
	 * Sets the indicativo of this municipio.
	 *
	 * @param indicativo the indicativo of this municipio
	 */
	public void setIndicativo(int indicativo);

	/**
	 * Returns the id circuito of this municipio.
	 *
	 * @return the id circuito of this municipio
	 */
	public int getIdCircuito();

	/**
	 * Sets the id circuito of this municipio.
	 *
	 * @param idCircuito the id circuito of this municipio
	 */
	public void setIdCircuito(int idCircuito);

	/**
	 * Returns the id circuito administrativo of this municipio.
	 *
	 * @return the id circuito administrativo of this municipio
	 */
	public int getIdCircuitoAdministrativo();

	/**
	 * Sets the id circuito administrativo of this municipio.
	 *
	 * @param idCircuitoAdministrativo the id circuito administrativo of this municipio
	 */
	public void setIdCircuitoAdministrativo(int idCircuitoAdministrativo);

	/**
	 * Returns the id consejo seccional of this municipio.
	 *
	 * @return the id consejo seccional of this municipio
	 */
	public int getIdConsejoSeccional();

	/**
	 * Sets the id consejo seccional of this municipio.
	 *
	 * @param idConsejoSeccional the id consejo seccional of this municipio
	 */
	public void setIdConsejoSeccional(int idConsejoSeccional);

	/**
	 * Returns the id circuito disciplinario of this municipio.
	 *
	 * @return the id circuito disciplinario of this municipio
	 */
	public int getIdCircuitoDisciplinario();

	/**
	 * Sets the id circuito disciplinario of this municipio.
	 *
	 * @param idCircuitoDisciplinario the id circuito disciplinario of this municipio
	 */
	public void setIdCircuitoDisciplinario(int idCircuitoDisciplinario);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Municipio municipio);

	public int hashCode();

	public CacheModel<Municipio> toCacheModel();

	public Municipio toEscapedModel();

	public String toString();

	public String toXmlString();
}