/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RelacionUsuarioConsejo service. Represents a row in the &quot;REL_USUARIO_CONSEJOS_SEC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.despachos_judiciales.entities.model.impl.RelacionUsuarioConsejoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.despachos_judiciales.entities.model.impl.RelacionUsuarioConsejoImpl}.
 * </p>
 *
 * @author mariza
 * @see RelacionUsuarioConsejo
 * @see la.netco.despachos_judiciales.entities.model.impl.RelacionUsuarioConsejoImpl
 * @see la.netco.despachos_judiciales.entities.model.impl.RelacionUsuarioConsejoModelImpl
 * @generated
 */
public interface RelacionUsuarioConsejoModel extends BaseModel<RelacionUsuarioConsejo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a relacion usuario consejo model instance should use the {@link RelacionUsuarioConsejo} interface instead.
	 */

	/**
	 * Returns the primary key of this relacion usuario consejo.
	 *
	 * @return the primary key of this relacion usuario consejo
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this relacion usuario consejo.
	 *
	 * @param primaryKey the primary key of this relacion usuario consejo
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id consejo sec of this relacion usuario consejo.
	 *
	 * @return the id consejo sec of this relacion usuario consejo
	 */
	public int getIdConsejoSec();

	/**
	 * Sets the id consejo sec of this relacion usuario consejo.
	 *
	 * @param idConsejoSec the id consejo sec of this relacion usuario consejo
	 */
	public void setIdConsejoSec(int idConsejoSec);

	/**
	 * Returns the usuario portal of this relacion usuario consejo.
	 *
	 * @return the usuario portal of this relacion usuario consejo
	 */
	@AutoEscape
	public String getUsuarioPortal();

	/**
	 * Sets the usuario portal of this relacion usuario consejo.
	 *
	 * @param usuarioPortal the usuario portal of this relacion usuario consejo
	 */
	public void setUsuarioPortal(String usuarioPortal);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(RelacionUsuarioConsejo relacionUsuarioConsejo);

	public int hashCode();

	public CacheModel<RelacionUsuarioConsejo> toCacheModel();

	public RelacionUsuarioConsejo toEscapedModel();

	public String toString();

	public String toXmlString();
}