/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.despachos_judiciales.entities.model.Trabajador;
import la.netco.despachos_judiciales.entities.model.TrabajadorModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Trabajador service. Represents a row in the &quot;ADM_TRABAJADORES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.despachos_judiciales.entities.model.TrabajadorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrabajadorImpl}.
 * </p>
 *
 * @author mariza
 * @see TrabajadorImpl
 * @see la.netco.despachos_judiciales.entities.model.Trabajador
 * @see la.netco.despachos_judiciales.entities.model.TrabajadorModel
 * @generated
 */
public class TrabajadorModelImpl extends BaseModelImpl<Trabajador>
	implements TrabajadorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trabajador model instance should use the {@link la.netco.despachos_judiciales.entities.model.Trabajador} interface instead.
	 */
	public static final String TABLE_NAME = "ADM_TRABAJADORES";
	public static final Object[][] TABLE_COLUMNS = {
			{ "TRA_CEDULA", Types.VARCHAR },
			{ "TRA_NOMBRES", Types.VARCHAR },
			{ "TRA_APELLIDOS", Types.VARCHAR },
			{ "TRA_ESPECIALIDAD", Types.VARCHAR },
			{ "TRA_CORREO_ELECTRONICO", Types.VARCHAR },
			{ "TRA_TELEFONOS_OFICINA", Types.VARCHAR },
			{ "TRA_CARRERA", Types.BIGINT },
			{ "TRA_TIPO_TRABAJADOR", Types.BIGINT },
			{ "TRA_TIPO_CONTRATO", Types.BIGINT },
			{ "TRA_SEXO", Types.VARCHAR },
			{ "TRA_FECHA_NACIMIENTO", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table ADM_TRABAJADORES (TRA_CEDULA VARCHAR(75) not null primary key,TRA_NOMBRES VARCHAR(75) null,TRA_APELLIDOS VARCHAR(75) null,TRA_ESPECIALIDAD VARCHAR(75) null,TRA_CORREO_ELECTRONICO VARCHAR(75) null,TRA_TELEFONOS_OFICINA VARCHAR(75) null,TRA_CARRERA LONG,TRA_TIPO_TRABAJADOR LONG,TRA_TIPO_CONTRATO LONG,TRA_SEXO VARCHAR(75) null,TRA_FECHA_NACIMIENTO DATE null)";
	public static final String TABLE_SQL_DROP = "drop table ADM_TRABAJADORES";
	public static final String DATA_SOURCE = "csjDespachosDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.despachos_judiciales.entities.model.Trabajador"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.despachos_judiciales.entities.model.Trabajador"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.despachos_judiciales.entities.model.Trabajador"));

	public TrabajadorModelImpl() {
	}

	public String getPrimaryKey() {
		return _cedula;
	}

	public void setPrimaryKey(String primaryKey) {
		setCedula(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _cedula;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return Trabajador.class;
	}

	public String getModelClassName() {
		return Trabajador.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cedula", getCedula());
		attributes.put("nombres", getNombres());
		attributes.put("apellidos", getApellidos());
		attributes.put("especialidad", getEspecialidad());
		attributes.put("correo_electronico", getCorreo_electronico());
		attributes.put("telefonos_oficina", getTelefonos_oficina());
		attributes.put("carrera", getCarrera());
		attributes.put("tipo_trabajador", getTipo_trabajador());
		attributes.put("tipo_contrato", getTipo_contrato());
		attributes.put("sexo", getSexo());
		attributes.put("fecha_nacimiento", getFecha_nacimiento());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String cedula = (String)attributes.get("cedula");

		if (cedula != null) {
			setCedula(cedula);
		}

		String nombres = (String)attributes.get("nombres");

		if (nombres != null) {
			setNombres(nombres);
		}

		String apellidos = (String)attributes.get("apellidos");

		if (apellidos != null) {
			setApellidos(apellidos);
		}

		String especialidad = (String)attributes.get("especialidad");

		if (especialidad != null) {
			setEspecialidad(especialidad);
		}

		String correo_electronico = (String)attributes.get("correo_electronico");

		if (correo_electronico != null) {
			setCorreo_electronico(correo_electronico);
		}

		String telefonos_oficina = (String)attributes.get("telefonos_oficina");

		if (telefonos_oficina != null) {
			setTelefonos_oficina(telefonos_oficina);
		}

		Long carrera = (Long)attributes.get("carrera");

		if (carrera != null) {
			setCarrera(carrera);
		}

		Long tipo_trabajador = (Long)attributes.get("tipo_trabajador");

		if (tipo_trabajador != null) {
			setTipo_trabajador(tipo_trabajador);
		}

		Long tipo_contrato = (Long)attributes.get("tipo_contrato");

		if (tipo_contrato != null) {
			setTipo_contrato(tipo_contrato);
		}

		String sexo = (String)attributes.get("sexo");

		if (sexo != null) {
			setSexo(sexo);
		}

		Date fecha_nacimiento = (Date)attributes.get("fecha_nacimiento");

		if (fecha_nacimiento != null) {
			setFecha_nacimiento(fecha_nacimiento);
		}
	}

	public String getCedula() {
		if (_cedula == null) {
			return StringPool.BLANK;
		}
		else {
			return _cedula;
		}
	}

	public void setCedula(String cedula) {
		_cedula = cedula;
	}

	public String getNombres() {
		if (_nombres == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombres;
		}
	}

	public void setNombres(String nombres) {
		_nombres = nombres;
	}

	public String getApellidos() {
		if (_apellidos == null) {
			return StringPool.BLANK;
		}
		else {
			return _apellidos;
		}
	}

	public void setApellidos(String apellidos) {
		_apellidos = apellidos;
	}

	public String getEspecialidad() {
		if (_especialidad == null) {
			return StringPool.BLANK;
		}
		else {
			return _especialidad;
		}
	}

	public void setEspecialidad(String especialidad) {
		_especialidad = especialidad;
	}

	public String getCorreo_electronico() {
		if (_correo_electronico == null) {
			return StringPool.BLANK;
		}
		else {
			return _correo_electronico;
		}
	}

	public void setCorreo_electronico(String correo_electronico) {
		_correo_electronico = correo_electronico;
	}

	public String getTelefonos_oficina() {
		if (_telefonos_oficina == null) {
			return StringPool.BLANK;
		}
		else {
			return _telefonos_oficina;
		}
	}

	public void setTelefonos_oficina(String telefonos_oficina) {
		_telefonos_oficina = telefonos_oficina;
	}

	public long getCarrera() {
		return _carrera;
	}

	public void setCarrera(long carrera) {
		_carrera = carrera;
	}

	public long getTipo_trabajador() {
		return _tipo_trabajador;
	}

	public void setTipo_trabajador(long tipo_trabajador) {
		_tipo_trabajador = tipo_trabajador;
	}

	public long getTipo_contrato() {
		return _tipo_contrato;
	}

	public void setTipo_contrato(long tipo_contrato) {
		_tipo_contrato = tipo_contrato;
	}

	public String getSexo() {
		if (_sexo == null) {
			return StringPool.BLANK;
		}
		else {
			return _sexo;
		}
	}

	public void setSexo(String sexo) {
		_sexo = sexo;
	}

	public Date getFecha_nacimiento() {
		return _fecha_nacimiento;
	}

	public void setFecha_nacimiento(Date fecha_nacimiento) {
		_fecha_nacimiento = fecha_nacimiento;
	}

	@Override
	public Trabajador toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Trabajador)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		TrabajadorImpl trabajadorImpl = new TrabajadorImpl();

		trabajadorImpl.setCedula(getCedula());
		trabajadorImpl.setNombres(getNombres());
		trabajadorImpl.setApellidos(getApellidos());
		trabajadorImpl.setEspecialidad(getEspecialidad());
		trabajadorImpl.setCorreo_electronico(getCorreo_electronico());
		trabajadorImpl.setTelefonos_oficina(getTelefonos_oficina());
		trabajadorImpl.setCarrera(getCarrera());
		trabajadorImpl.setTipo_trabajador(getTipo_trabajador());
		trabajadorImpl.setTipo_contrato(getTipo_contrato());
		trabajadorImpl.setSexo(getSexo());
		trabajadorImpl.setFecha_nacimiento(getFecha_nacimiento());

		trabajadorImpl.resetOriginalValues();

		return trabajadorImpl;
	}

	public int compareTo(Trabajador trabajador) {
		String primaryKey = trabajador.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Trabajador trabajador = null;

		try {
			trabajador = (Trabajador)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = trabajador.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Trabajador> toCacheModel() {
		TrabajadorCacheModel trabajadorCacheModel = new TrabajadorCacheModel();

		trabajadorCacheModel.cedula = getCedula();

		String cedula = trabajadorCacheModel.cedula;

		if ((cedula != null) && (cedula.length() == 0)) {
			trabajadorCacheModel.cedula = null;
		}

		trabajadorCacheModel.nombres = getNombres();

		String nombres = trabajadorCacheModel.nombres;

		if ((nombres != null) && (nombres.length() == 0)) {
			trabajadorCacheModel.nombres = null;
		}

		trabajadorCacheModel.apellidos = getApellidos();

		String apellidos = trabajadorCacheModel.apellidos;

		if ((apellidos != null) && (apellidos.length() == 0)) {
			trabajadorCacheModel.apellidos = null;
		}

		trabajadorCacheModel.especialidad = getEspecialidad();

		String especialidad = trabajadorCacheModel.especialidad;

		if ((especialidad != null) && (especialidad.length() == 0)) {
			trabajadorCacheModel.especialidad = null;
		}

		trabajadorCacheModel.correo_electronico = getCorreo_electronico();

		String correo_electronico = trabajadorCacheModel.correo_electronico;

		if ((correo_electronico != null) && (correo_electronico.length() == 0)) {
			trabajadorCacheModel.correo_electronico = null;
		}

		trabajadorCacheModel.telefonos_oficina = getTelefonos_oficina();

		String telefonos_oficina = trabajadorCacheModel.telefonos_oficina;

		if ((telefonos_oficina != null) && (telefonos_oficina.length() == 0)) {
			trabajadorCacheModel.telefonos_oficina = null;
		}

		trabajadorCacheModel.carrera = getCarrera();

		trabajadorCacheModel.tipo_trabajador = getTipo_trabajador();

		trabajadorCacheModel.tipo_contrato = getTipo_contrato();

		trabajadorCacheModel.sexo = getSexo();

		String sexo = trabajadorCacheModel.sexo;

		if ((sexo != null) && (sexo.length() == 0)) {
			trabajadorCacheModel.sexo = null;
		}

		Date fecha_nacimiento = getFecha_nacimiento();

		if (fecha_nacimiento != null) {
			trabajadorCacheModel.fecha_nacimiento = fecha_nacimiento.getTime();
		}
		else {
			trabajadorCacheModel.fecha_nacimiento = Long.MIN_VALUE;
		}

		return trabajadorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{cedula=");
		sb.append(getCedula());
		sb.append(", nombres=");
		sb.append(getNombres());
		sb.append(", apellidos=");
		sb.append(getApellidos());
		sb.append(", especialidad=");
		sb.append(getEspecialidad());
		sb.append(", correo_electronico=");
		sb.append(getCorreo_electronico());
		sb.append(", telefonos_oficina=");
		sb.append(getTelefonos_oficina());
		sb.append(", carrera=");
		sb.append(getCarrera());
		sb.append(", tipo_trabajador=");
		sb.append(getTipo_trabajador());
		sb.append(", tipo_contrato=");
		sb.append(getTipo_contrato());
		sb.append(", sexo=");
		sb.append(getSexo());
		sb.append(", fecha_nacimiento=");
		sb.append(getFecha_nacimiento());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("la.netco.despachos_judiciales.entities.model.Trabajador");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cedula</column-name><column-value><![CDATA[");
		sb.append(getCedula());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombres</column-name><column-value><![CDATA[");
		sb.append(getNombres());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>apellidos</column-name><column-value><![CDATA[");
		sb.append(getApellidos());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>especialidad</column-name><column-value><![CDATA[");
		sb.append(getEspecialidad());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>correo_electronico</column-name><column-value><![CDATA[");
		sb.append(getCorreo_electronico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telefonos_oficina</column-name><column-value><![CDATA[");
		sb.append(getTelefonos_oficina());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>carrera</column-name><column-value><![CDATA[");
		sb.append(getCarrera());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipo_trabajador</column-name><column-value><![CDATA[");
		sb.append(getTipo_trabajador());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipo_contrato</column-name><column-value><![CDATA[");
		sb.append(getTipo_contrato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sexo</column-name><column-value><![CDATA[");
		sb.append(getSexo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_nacimiento</column-name><column-value><![CDATA[");
		sb.append(getFecha_nacimiento());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Trabajador.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Trabajador.class
		};
	private String _cedula;
	private String _nombres;
	private String _apellidos;
	private String _especialidad;
	private String _correo_electronico;
	private String _telefonos_oficina;
	private long _carrera;
	private long _tipo_trabajador;
	private long _tipo_contrato;
	private String _sexo;
	private Date _fecha_nacimiento;
	private Trabajador _escapedModelProxy;
}