/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Distrito service. Represents a row in the &quot;GLO_DISTRITOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.despachos_judiciales.entities.model.impl.DistritoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.despachos_judiciales.entities.model.impl.DistritoImpl}.
 * </p>
 *
 * @author mariza
 * @see Distrito
 * @see la.netco.despachos_judiciales.entities.model.impl.DistritoImpl
 * @see la.netco.despachos_judiciales.entities.model.impl.DistritoModelImpl
 * @generated
 */
public interface DistritoModel extends BaseModel<Distrito> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a distrito model instance should use the {@link Distrito} interface instead.
	 */

	/**
	 * Returns the primary key of this distrito.
	 *
	 * @return the primary key of this distrito
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this distrito.
	 *
	 * @param primaryKey the primary key of this distrito
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the codigo of this distrito.
	 *
	 * @return the codigo of this distrito
	 */
	public int getCodigo();

	/**
	 * Sets the codigo of this distrito.
	 *
	 * @param codigo the codigo of this distrito
	 */
	public void setCodigo(int codigo);

	/**
	 * Returns the nombre of this distrito.
	 *
	 * @return the nombre of this distrito
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this distrito.
	 *
	 * @param nombre the nombre of this distrito
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the id consejo_sec of this distrito.
	 *
	 * @return the id consejo_sec of this distrito
	 */
	public int getIdConsejo_sec();

	/**
	 * Sets the id consejo_sec of this distrito.
	 *
	 * @param idConsejo_sec the id consejo_sec of this distrito
	 */
	public void setIdConsejo_sec(int idConsejo_sec);

	/**
	 * Returns the jurisdiccion of this distrito.
	 *
	 * @return the jurisdiccion of this distrito
	 */
	@AutoEscape
	public String getJurisdiccion();

	/**
	 * Sets the jurisdiccion of this distrito.
	 *
	 * @param jurisdiccion the jurisdiccion of this distrito
	 */
	public void setJurisdiccion(String jurisdiccion);

	/**
	 * Returns the codigo_dane of this distrito.
	 *
	 * @return the codigo_dane of this distrito
	 */
	@AutoEscape
	public String getCodigo_dane();

	/**
	 * Sets the codigo_dane of this distrito.
	 *
	 * @param codigo_dane the codigo_dane of this distrito
	 */
	public void setCodigo_dane(String codigo_dane);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Distrito distrito);

	public int hashCode();

	public CacheModel<Distrito> toCacheModel();

	public Distrito toEscapedModel();

	public String toString();

	public String toXmlString();
}