/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.despachos_judiciales.entities.model.Distrito;
import la.netco.despachos_judiciales.entities.model.DistritoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Distrito service. Represents a row in the &quot;GLO_DISTRITOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.despachos_judiciales.entities.model.DistritoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DistritoImpl}.
 * </p>
 *
 * @author mariza
 * @see DistritoImpl
 * @see la.netco.despachos_judiciales.entities.model.Distrito
 * @see la.netco.despachos_judiciales.entities.model.DistritoModel
 * @generated
 */
public class DistritoModelImpl extends BaseModelImpl<Distrito>
	implements DistritoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a distrito model instance should use the {@link la.netco.despachos_judiciales.entities.model.Distrito} interface instead.
	 */
	public static final String TABLE_NAME = "GLO_DISTRITOS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "DIS_CODIGO", Types.INTEGER },
			{ "DIS_NOMBRE", Types.VARCHAR },
			{ "DIS_CONSEJO_SEC", Types.INTEGER },
			{ "DIS_JURISDICCION", Types.VARCHAR },
			{ "DIS_CODIGO_DANE", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GLO_DISTRITOS (DIS_CODIGO INTEGER not null primary key,DIS_NOMBRE VARCHAR(75) null,DIS_CONSEJO_SEC INTEGER,DIS_JURISDICCION VARCHAR(75) null,DIS_CODIGO_DANE VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GLO_DISTRITOS";
	public static final String DATA_SOURCE = "csjDespachosDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.despachos_judiciales.entities.model.Distrito"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.despachos_judiciales.entities.model.Distrito"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.despachos_judiciales.entities.model.Distrito"));

	public DistritoModelImpl() {
	}

	public int getPrimaryKey() {
		return _codigo;
	}

	public void setPrimaryKey(int primaryKey) {
		setCodigo(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_codigo);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return Distrito.class;
	}

	public String getModelClassName() {
		return Distrito.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("codigo", getCodigo());
		attributes.put("nombre", getNombre());
		attributes.put("idConsejo_sec", getIdConsejo_sec());
		attributes.put("jurisdiccion", getJurisdiccion());
		attributes.put("codigo_dane", getCodigo_dane());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer codigo = (Integer)attributes.get("codigo");

		if (codigo != null) {
			setCodigo(codigo);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}

		Integer idConsejo_sec = (Integer)attributes.get("idConsejo_sec");

		if (idConsejo_sec != null) {
			setIdConsejo_sec(idConsejo_sec);
		}

		String jurisdiccion = (String)attributes.get("jurisdiccion");

		if (jurisdiccion != null) {
			setJurisdiccion(jurisdiccion);
		}

		String codigo_dane = (String)attributes.get("codigo_dane");

		if (codigo_dane != null) {
			setCodigo_dane(codigo_dane);
		}
	}

	public int getCodigo() {
		return _codigo;
	}

	public void setCodigo(int codigo) {
		_codigo = codigo;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	public int getIdConsejo_sec() {
		return _idConsejo_sec;
	}

	public void setIdConsejo_sec(int idConsejo_sec) {
		_idConsejo_sec = idConsejo_sec;
	}

	public String getJurisdiccion() {
		if (_jurisdiccion == null) {
			return StringPool.BLANK;
		}
		else {
			return _jurisdiccion;
		}
	}

	public void setJurisdiccion(String jurisdiccion) {
		_jurisdiccion = jurisdiccion;
	}

	public String getCodigo_dane() {
		if (_codigo_dane == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigo_dane;
		}
	}

	public void setCodigo_dane(String codigo_dane) {
		_codigo_dane = codigo_dane;
	}

	@Override
	public Distrito toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Distrito)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		DistritoImpl distritoImpl = new DistritoImpl();

		distritoImpl.setCodigo(getCodigo());
		distritoImpl.setNombre(getNombre());
		distritoImpl.setIdConsejo_sec(getIdConsejo_sec());
		distritoImpl.setJurisdiccion(getJurisdiccion());
		distritoImpl.setCodigo_dane(getCodigo_dane());

		distritoImpl.resetOriginalValues();

		return distritoImpl;
	}

	public int compareTo(Distrito distrito) {
		int primaryKey = distrito.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Distrito distrito = null;

		try {
			distrito = (Distrito)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = distrito.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Distrito> toCacheModel() {
		DistritoCacheModel distritoCacheModel = new DistritoCacheModel();

		distritoCacheModel.codigo = getCodigo();

		distritoCacheModel.nombre = getNombre();

		String nombre = distritoCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			distritoCacheModel.nombre = null;
		}

		distritoCacheModel.idConsejo_sec = getIdConsejo_sec();

		distritoCacheModel.jurisdiccion = getJurisdiccion();

		String jurisdiccion = distritoCacheModel.jurisdiccion;

		if ((jurisdiccion != null) && (jurisdiccion.length() == 0)) {
			distritoCacheModel.jurisdiccion = null;
		}

		distritoCacheModel.codigo_dane = getCodigo_dane();

		String codigo_dane = distritoCacheModel.codigo_dane;

		if ((codigo_dane != null) && (codigo_dane.length() == 0)) {
			distritoCacheModel.codigo_dane = null;
		}

		return distritoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{codigo=");
		sb.append(getCodigo());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append(", idConsejo_sec=");
		sb.append(getIdConsejo_sec());
		sb.append(", jurisdiccion=");
		sb.append(getJurisdiccion());
		sb.append(", codigo_dane=");
		sb.append(getCodigo_dane());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("la.netco.despachos_judiciales.entities.model.Distrito");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>codigo</column-name><column-value><![CDATA[");
		sb.append(getCodigo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idConsejo_sec</column-name><column-value><![CDATA[");
		sb.append(getIdConsejo_sec());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jurisdiccion</column-name><column-value><![CDATA[");
		sb.append(getJurisdiccion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codigo_dane</column-name><column-value><![CDATA[");
		sb.append(getCodigo_dane());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Distrito.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Distrito.class
		};
	private int _codigo;
	private String _nombre;
	private int _idConsejo_sec;
	private String _jurisdiccion;
	private String _codigo_dane;
	private Distrito _escapedModelProxy;
}