/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.despachos_judiciales.entities.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Despacho service. Represents a row in the &quot;ADM_DESPACHOS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.despachos_judiciales.entities.model.impl.DespachoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.despachos_judiciales.entities.model.impl.DespachoImpl}.
 * </p>
 *
 * @author mariza
 * @see Despacho
 * @see la.netco.despachos_judiciales.entities.model.impl.DespachoImpl
 * @see la.netco.despachos_judiciales.entities.model.impl.DespachoModelImpl
 * @generated
 */
public interface DespachoModel extends BaseModel<Despacho> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a despacho model instance should use the {@link Despacho} interface instead.
	 */

	/**
	 * Returns the primary key of this despacho.
	 *
	 * @return the primary key of this despacho
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this despacho.
	 *
	 * @param primaryKey the primary key of this despacho
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codigo of this despacho.
	 *
	 * @return the codigo of this despacho
	 */
	@AutoEscape
	public String getCodigo();

	/**
	 * Sets the codigo of this despacho.
	 *
	 * @param codigo the codigo of this despacho
	 */
	public void setCodigo(String codigo);

	/**
	 * Returns the id departamento of this despacho.
	 *
	 * @return the id departamento of this despacho
	 */
	public int getIdDepartamento();

	/**
	 * Sets the id departamento of this despacho.
	 *
	 * @param idDepartamento the id departamento of this despacho
	 */
	public void setIdDepartamento(int idDepartamento);

	/**
	 * Returns the id municipio of this despacho.
	 *
	 * @return the id municipio of this despacho
	 */
	public int getIdMunicipio();

	/**
	 * Sets the id municipio of this despacho.
	 *
	 * @param idMunicipio the id municipio of this despacho
	 */
	public void setIdMunicipio(int idMunicipio);

	/**
	 * Returns the id entidad of this despacho.
	 *
	 * @return the id entidad of this despacho
	 */
	public int getIdEntidad();

	/**
	 * Sets the id entidad of this despacho.
	 *
	 * @param idEntidad the id entidad of this despacho
	 */
	public void setIdEntidad(int idEntidad);

	/**
	 * Returns the id especialidad of this despacho.
	 *
	 * @return the id especialidad of this despacho
	 */
	public int getIdEspecialidad();

	/**
	 * Sets the id especialidad of this despacho.
	 *
	 * @param idEspecialidad the id especialidad of this despacho
	 */
	public void setIdEspecialidad(int idEspecialidad);

	/**
	 * Returns the consecutivo of this despacho.
	 *
	 * @return the consecutivo of this despacho
	 */
	@AutoEscape
	public String getConsecutivo();

	/**
	 * Sets the consecutivo of this despacho.
	 *
	 * @param consecutivo the consecutivo of this despacho
	 */
	public void setConsecutivo(String consecutivo);

	/**
	 * Returns the nombre of this despacho.
	 *
	 * @return the nombre of this despacho
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this despacho.
	 *
	 * @param nombre the nombre of this despacho
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the direccion of this despacho.
	 *
	 * @return the direccion of this despacho
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this despacho.
	 *
	 * @param direccion the direccion of this despacho
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the telefonos of this despacho.
	 *
	 * @return the telefonos of this despacho
	 */
	@AutoEscape
	public String getTelefonos();

	/**
	 * Sets the telefonos of this despacho.
	 *
	 * @param telefonos the telefonos of this despacho
	 */
	public void setTelefonos(String telefonos);

	/**
	 * Returns the correo_electronico of this despacho.
	 *
	 * @return the correo_electronico of this despacho
	 */
	@AutoEscape
	public String getCorreo_electronico();

	/**
	 * Sets the correo_electronico of this despacho.
	 *
	 * @param correo_electronico the correo_electronico of this despacho
	 */
	public void setCorreo_electronico(String correo_electronico);

	/**
	 * Returns the acuerdo of this despacho.
	 *
	 * @return the acuerdo of this despacho
	 */
	@AutoEscape
	public String getAcuerdo();

	/**
	 * Sets the acuerdo of this despacho.
	 *
	 * @param acuerdo the acuerdo of this despacho
	 */
	public void setAcuerdo(String acuerdo);

	/**
	 * Returns the estado of this despacho.
	 *
	 * @return the estado of this despacho
	 */
	public long getEstado();

	/**
	 * Sets the estado of this despacho.
	 *
	 * @param estado the estado of this despacho
	 */
	public void setEstado(long estado);

	/**
	 * Returns the fax of this despacho.
	 *
	 * @return the fax of this despacho
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this despacho.
	 *
	 * @param fax the fax of this despacho
	 */
	public void setFax(String fax);

	/**
	 * Returns the horario_atencion of this despacho.
	 *
	 * @return the horario_atencion of this despacho
	 */
	@AutoEscape
	public String getHorario_atencion();

	/**
	 * Sets the horario_atencion of this despacho.
	 *
	 * @param horario_atencion the horario_atencion of this despacho
	 */
	public void setHorario_atencion(String horario_atencion);

	/**
	 * Returns the fecha_act of this despacho.
	 *
	 * @return the fecha_act of this despacho
	 */
	public Date getFecha_act();

	/**
	 * Sets the fecha_act of this despacho.
	 *
	 * @param fecha_act the fecha_act of this despacho
	 */
	public void setFecha_act(Date fecha_act);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Despacho despacho);

	public int hashCode();

	public CacheModel<Despacho> toCacheModel();

	public Despacho toEscapedModel();

	public String toString();

	public String toXmlString();
}